version: "1.0"
info:
  model: int-scaffold
packages:
- name: Test26091Project
  gitServerName: testEdgeProjects
  gitUrl: https://github.com/rlakshitha0912/Test26091Project
  gitUsername: rlakshitha0912
  gitToken: edge.scaffolding.Test26091Project.testEdgeProjects.gitToken
  gitBranch: main
